platform :ios, ’9.0’
use_frameworks!

target 'iOSTestingExample' do
end

target 'iOSTestingExampleTests' do
    pod 'FBSnapshotTestCase', '~> 2.1.4'
    pod 'SnapKit'
    pod 'OCMock'
end

target 'iOSTestingExampleUITests' do
end

target 'iOSTestingExampleKIFTests' do
    pod 'KIF', :configurations => ['Debug']
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
