# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'iOSTestingExample' do

end

target 'iOSTestingExampleTests' do

end

target 'iOSTestingExampleUITests' do

end

