platform :ios, ‘9.0’
use_frameworks!

target 'MobileApplicationTesting' do
pod 'Firebase', '>= 2.5.1'
end

target 'MobileApplicationTestingTests' do
    pod 'FBSnapshotTestCase', '~> 2.1'
    pod 'SnapKit', '~> 0.20'
    pod 'OCMock', '~> 3.3'
end

target 'MobileApplicationTestingUITests' do
end

target 'MobileApplicationTestingKIFTests' do
    pod 'KIF', '~> 3.4', :configurations => ['Debug']
end
