fastlane_version "1.105.2"
default_platform :ios

platform :ios do

  desc "Runs unit and UI tests"
  lane :test do

  scan

  slather(
    source_directory: "..",
    proj: 'iOSTestingExample.xcodeproj',
    workspace: "iOSTestingExample.xcworkspace",
    scheme: 'iOSTestingExample',
    html: true,
    use_bundle_exec: true
  )
  end

end
